global:
  host: chart-example.local
  cors_allowed_origin: "*"

version: 0.0.1

image:
  repository: ghcr.io/unis-svalbard-weather-information/swi-elevationapi:latest
  pullPolicy: IfNotPresent

volumes:
  name: elevationapivolume
  mountPath: /code/data
  readOnly: false

networks:
  - swi_network

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: metobs-api-ingress
  annotations: {}
  hosts:
    - subhost: ""
      paths:
        - path: /public
          pathType: Prefix
  tls: []
