apiVersion: apps/v1
kind: Deployment
metadata:
  name: swi-metobs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swi-metobs-backend
  template:
    metadata:
      labels:
        app: swi-metobs-backend
    spec:
      containers:
        - name: swi-metobs-backend
          image: "{{ .Values.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: API_ROOT_PATH
              value: "{{ .Values.environment.API_ROOT_PATH }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.global.cors_allowed_origin }}"
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
              readOnly: {{ .Values.volumes.readOnly }}
      volumes:
        - name: metobsvolume
          persistentVolumeClaim:
            claimName: metobsvolume
